user.name = "David Crespo"
user.email = "david.crespo@oxidecomputer.com"

[ui]
pager = "delta"
default-command = "st"
diff-editor = ":builtin"

[ui.diff]
format = "git"

[aliases]
d = ["diff"]
dm = ["describe", "-m"]
dt = ["diff", "--tool", "difft"]
rp = ["log", "--no-graph", "-T", "commit_id"]
ds = ["diff", "--stat"]
r = ["log"]
cm = ["commit", "-m"]

[merge-tools.difft]
diff-args = ["--color=always", "$left", "$right"]

[template-aliases]
# Username part of the email address
'format_short_signature(signature)' = 'signature.username()'
