[user]
name = "David Crespo"
email = "crespo.dm@gmail.com"

[[--scope]]
--when.repositories = ["~/oxide"]
[--scope.user]
email = "david.crespo@oxidecomputer.com"

[ui]
pager = "delta"
default-command = "st"
diff-editor = ":builtin"
merge-editor = "vscode"

[ui.diff]
format = "git"

[aliases]
d = ["diff"]
dm = ["describe", "-m"]
dt = ["diff", "--tool", "difft"]
rp = ["log", "--no-graph", "-T", "commit_id"]
ds = ["diff", "--stat"]
r = ["log"]
cm = ["commit", "-m"]

[merge-tools.difft]
diff-args = ["--color=always", "$left", "$right"]

[template-aliases]
# Username part of the email address
'format_short_signature(signature)' = 'signature.email().local()'

# format_commit_summary_with_refs minus git commit
'zsh_prompt_summary(commit, refs)' = '''
separate(" ",
  format_short_change_id_with_hidden_and_divergent_info(commit),
  separate(commit_summary_separator,
    refs,
    separate(" ",
      if(commit.conflict(), label("conflict", "(conflict)")),
      if(commit.description(),
        if(commit.empty(), label("empty", "(empty) ")) ++ commit.description().first_line(),
        if(commit.empty(), label("empty", "(empty)"), label("empty", "(no desc)")),
      ),
    ),
  ),
)
'''

# logic for the empty + desc above
# 
# if desc
#   if empty
#     show (empty)
#   show desc 
# else
#   if empty
#     just show (empty)
#   else
#     show (no desc)
