user.name = "David Crespo"
user.email = "david.crespo@oxidecomputer.com"

[ui]
default-command = ["st"]
pager = "delta"

[ui.diff]
format = "git"

[aliases]
d = ["diff"]

[template-aliases]
# Username part of the email address
'format_short_signature(signature)' = 'signature.username()'
