theme = "ayu_evolve2"

[editor]
cursorline = true
auto-pairs = false
jump-label-alphabet = "asdghklqwertyuiopzxcvbnmfj"
file-picker.hidden = false # show hidden files
cursor-shape.insert = "bar"
lsp.display-messages = true
lsp.display-progress-messages = true
soft-wrap.enable = true
whitespace.render.nbsp = "all"
shell = ["zsh", "-c"]
popup-border = "all"
continue-comments = false

statusline.right = [
  "register",
  "position",
  "search-position",
  "diagnostics",
  "workspace-diagnostics",
  "total-line-numbers",
  "selections"
]

# See https://github.com/helix-editor/helix/pull/11700
search.max-matches = 1000

[keys.normal]
Cmd-s = ":w"
A-w = ":bc"
"=" = ":reflow"
X = "select_line_above"
x = "select_line_below"
# make it so you can get back to where you were before % with ctrl-o
"%" = ["save_selection", "select_all"]
# Cmd-h only works if you override the macOS default by binding Hide Ghostty to
# ⌘I in Keyboard > Keyboard shortcuts > App shortcuts
Cmd-h = "jump_view_left"
Cmd-j = "jump_view_down"
Cmd-k = "jump_view_up"
Cmd-l = "jump_view_right"
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
C-r = ":rla"

# open current line on github.com
C-b = ":sh gh browse %{buffer_name}:%{cursor_line} -c=%sh{latest_pushed_commit}"
# show blame for current line
C-B = ":sh git blame --date=short -L %{cursor_line},+1 %{buffer_name} | sed -E 's/[0-9]+).*//' | sed 's/(//g'"
tab = "@:pipe hxai -m 235b "

# hxai is defined in bin/hxai.ts
[keys.normal.L]
r = "@:pipe hxai "
s = "@:pipe hxai -m sonnet "
S = "@:pipe hxai -m sonnet -f %{buffer_name} "
g = "@:pipe hxai -m gpt-5 "
G = "@:pipe hxai -m gpt-5 -f %{buffer_name} "
o = "@:pipe hxai -m 120b "
O = "@:pipe hxai -m 120b -f %{buffer_name} "
q = "@:pipe hxai -m 235b "
Q = "@:pipe hxai -m 235b -f %{buffer_name} "

[keys.select.L]
r = "@:pipe hxai "
s = "@:pipe hxai -m sonnet "
S = "@:pipe hxai -m sonnet -f %{buffer_name} "
g = "@:pipe hxai -m gpt-5 "
G = "@:pipe hxai -m gpt-5 -f %{buffer_name} "
o = "@:pipe hxai -m 120b "
O = "@:pipe hxai -m 120b -f %{buffer_name} "
q = "@:pipe hxai -m 235b "
Q = "@:pipe hxai -m 235b -f %{buffer_name} "

[keys.normal.M]
f = ":toggle-option auto-format"
l = "@_ms(iconsole.log<esc>" # wrap current sel in console.log()
d = "@_ms(iconsole.dir<esc>" # wrap current sel in console.dir()
D = "@_ms(idbg!<esc>" # wrap current sel in dbg!()
s = ":pipe format_sql" # format_sql defined in .zshenv
c = ":echo %sh{copy_path %{buffer_name}}" #  copy_path defined in .zshenv

[keys.select.M]
f = ":toggle-option auto-format"
l = "@_ms(iconsole.log<esc>" # wrap current sel in console.log()
d = "@_ms(iconsole.dir<esc>" # wrap current sel in console.dir()
D = "@_ms(idbg!<esc>" # wrap current sel in dbg!()
s = ":pipe format_sql" # format_sql defined in .zshenv
c = ":echo %sh{copy_path %{buffer_name}}" #  copy_path defined in .zshenv

[keys.normal." "]
q = ":bc"
# remove these from the menu since I don't use them
F = "no_op"
G = "no_op"
p = "no_op"
P = "no_op"
R = "no_op"
Y = "no_op"
A-c = "no_op"

[keys.select]
x = "select_line_below"
X = "select_line_above"
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
tab = "@:pipe hxai -m 235b "
C-r = ":rla"

[keys.insert]
Cmd-s = ["normal_mode", ":w"]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
