theme = "ayu_evolve2"

[editor]
cursorline = true
auto-pairs = false
jump-label-alphabet = "asdghklqwertyuiopzxcvbnmfj"
file-picker.hidden = false # show hidden files
cursor-shape.insert = "bar"
lsp.display-messages = true
lsp.display-progress-messages = true
soft-wrap.enable = true
whitespace.render.nbsp = "all"
shell = ["zsh", "-c"]
popup-border = "all"
continue-comments = false

end-of-line-diagnostics = "hint"
inline-diagnostics.cursor-line = "warning"

statusline.right = [
  "register",
  "position",
  "search-position",
  "diagnostics",
  "workspace-diagnostics",
  "total-line-numbers",
  "selections"
]

# https://github.com/helix-editor/helix/pull/11497
# leaving out of my local thing for now
# rounded-corners = true

# https://github.com/helix-editor/helix/pull/11700
search.max-matches = 1000

[keys.normal]
Cmd-s = ":w"
Cmd-p = "file_picker"
A-w = ":bc"
"=" = ":reflow"
X = "select_line_above"
x = "select_line_below"
# make it so you can get back to where you were before % with ctrl-o
"%" = ["save_selection", "select_all"]
# Cmd-h only works if you override the macOS default by binding Hide Ghostty to
# ⌘I in Keyboard > Keyboard shortcuts > App shortcuts
Cmd-h = "jump_view_left"
Cmd-j = "jump_view_down"
Cmd-k = "jump_view_up"
Cmd-l = "jump_view_right"

C-b = ":sh gh browse %{buffer_name}:%{cursor_line} -c=%sh{latest_pushed_commit}"
C-B = ":sh git blame --date=short -L %{cursor_line},+1 %{buffer_name} | sed -E 's/[0-9]+).*//' | sed 's/(//g'"

[keys.normal.L]
b = [
  ':noop %sh{git blame --date=short "%{buffer_name}" > /tmp/blamecontents}',
  ':noop %sh{echo "%{cursor_line}" > /tmp/blameline}',
  ':o /tmp/blamecontents',
  ':goto %sh{cat /tmp/blameline}'
]
# pass -m <model> to override
r = "@|hxai "
e = "@|ai-edit "
f = ":toggle-option auto-format"
F = "@<C-s>maf<A-;>;"
# wrap current sel in console.log()
l = "@_ms(iconsole.log<esc>"
# wrap current sel in console.dir()
d = "@_ms(iconsole.dir<esc>"
# wrap current sel in dbg!()
D = "@_ms(idbg!<esc>"
# format SQL
s = ":pipe cockroach sqlfmt --print-width 80 --use-spaces"
# copy current file path
p = ":echo %sh{echo -n %{buffer_name} | pbcopy; echo \"Copied '%{buffer_name}' to system clipboard\"}"

[keys.select.L]
r = "@|hxai "
e = "@|ai-edit "
t = "@|stag<ret>sxxx<ret>c"
# wrap current sel in console.log()
l = "@_ms(iconsole.log<esc>"
# wrap current sel in console.dir()
d = "@_ms(iconsole.dir<esc>"
# wrap current sel in dbg!()
D = "@_ms(idbg!<esc>"
# format SQL
s = ":pipe cockroach sqlfmt --print-width 80 --use-spaces"

[keys.select]
Cmd-s = ":w"
x = "select_line_below"
X = "select_line_above"
Cmd-h = "jump_view_left"
Cmd-j = "jump_view_down"
Cmd-k = "jump_view_up"
Cmd-l = "jump_view_right"

[keys.insert]
Cmd-s = ["normal_mode", ":w"]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"

# let's clear out some stuff from the space menu
[keys.select." "]
F = "no_op"
G = "no_op"
[keys.normal." "]
F = "no_op"
G = "no_op"
