theme = "ayu_evolve2"

[editor]
cursorline = true
auto-pairs = false
jump-label-alphabet = "asdghklqwertyuiopzxcvbnmfj"
file-picker.hidden = false # show hidden files
cursor-shape.insert = "bar"
lsp.display-messages = true
soft-wrap.enable = true
whitespace.render.nbsp = "all"

end-of-line-diagnostics = "hint"
inline-diagnostics.cursor-line = "warning"

statusline.right = [
  "workspace-diagnostics",
  "diagnostics",
  "selections",
  "register",
  "position",
  "position-percentage",
  "total-line-numbers",
]

[keys.normal]
C-s = ":w"
A-w = ":bc"
"=" = ":reflow"
x = "select_line_below"
X = "select_line_above"

# need command expansions: https://github.com/helix-editor/helix/pull/11164
C-b = ":sh hxblame %{cwd} %{filename} %{linenumber}"
C-B = ":echo %sh{git blame --date=short -L %{linenumber},+1 %{filename} | sed -E 's/[0-9]+).*//' | sed 's/(//g'}"

[keys.select]
x = "select_line_below"
X = "select_line_above"

[keys.insert]
C-s = ["normal_mode", ":w"]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
