theme = "ayu_evolve2"

[editor]
cursorline = true
auto-pairs = false
jump-label-alphabet = "asdghklqwertyuiopzxcvbnmfj"
file-picker.hidden = false # show hidden files
cursor-shape.insert = "bar"
lsp.display-messages = true
soft-wrap.enable = true
whitespace.render.nbsp = "all"
shell = ["zsh", "-c"]
rounded-corners = true
popup-border = "all"

end-of-line-diagnostics = "hint"
inline-diagnostics.cursor-line = "warning"

statusline.right = [
  "workspace-diagnostics",
  "diagnostics",
  "selections",
  "register",
  "position",
  "total-line-numbers",
  "search-position",
]

[keys.normal]
C-s = ":w"
Cmd-s = ":w"
A-w = ":bc"
"=" = ":reflow"
X = "select_line_above"
x = "select_line_below"
C-p = "file_picker"

# need command expansions: https://github.com/helix-editor/helix/pull/11164
C-b = ":sh gh browse %{filename:repo_rel}:%{linenumber} -c=%sh{latest_pushed_commit}"
C-B = ":echo %sh{git blame --date=short -L %{linenumber},+1 %{filename} | sed -E 's/[0-9]+).*//' | sed 's/(//g'}"

[keys.normal.L]
r = "@|hxai " # claude by default, pass -m <model> to override
e = "@|ai-edit "
t = "@|stag<ret>sxxx<ret>c"
f = ":toggle-option auto-format"

[keys.select.L]
r = "@|hxai "
e = "@|ai-edit "
t = "@|stag<ret>sxxx<ret>c"

[keys.select]
x = "select_line_below"
X = "select_line_above"

[keys.insert]
C-s = ["normal_mode", ":w"]
Cmd-s = ["normal_mode", ":w"]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"

# let's clear out some stuff from the space menu
[keys.select." "]
F = "no_op"
G = "no_op"
[keys.normal." "]
F = "no_op"
G = "no_op"
