# Based on https://github.com/helix-editor/helix/blob/master/runtime/themes/base16_default_dark.toml
# by RayGervais <raygervais@hotmail.ca>

inherits = "base16_default_dark"

"ui.gutter" = { bg = "#1b1c1f" }
"ui.linenr" = { fg = "base03", bg = "#1b1c1f" }
"ui.cursorline.primary" = { bg = "#1b1c1f" }
"ui.cursorline.secondary" = { bg = "base01" }
"ui.virtual.jump-label" = { fg = "base0A" }

"variable" = "base05"
"variable.other.member" = "base08"

# colors come from here except I've darkened base00 from #1d1f21
# https://github.com/chriskempson/base16-vim/blob/3be3cd8/colors/base16-tomorrow-night.vim

[palette]
base00 = "#050506" # Default Background
base01 = "#282a2e" # Lighter Background (Used for status bars, line number and folding marks)
base02 = "#373b41" # Selection Background
base03 = "#969896" # Comments, Invisibles, Line Highlighting
base04 = "#b4b7b4" # Dark Foreground (Used for status bars)
base05 = "#c5c8c6" # Default Foreground, Caret, Delimiters, Operators
base06 = "#e0e0e0" # Light Foreground (Not often used)
base07 = "#ffffff" # Light Background (Not often used)
base08 = "#cc6666" # Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
base09 = "#de935f" # Integers, Boolean, Constants, XML Attributes, Markup Link Url
base0A = "#f0c674" # Classes, Markup Bold, Search Text Background
base0B = "#b5bd68" # Strings, Inherited Class, Markup Code, Diff Inserted
base0C = "#8abeb7" # Support, Regular Expressions, Escape Characters, Markup Quotes
base0D = "#81a2be" # Functions, Methods, Attribute IDs, Headings
base0E = "#b294bb" # Keywords, Storage, Selector, Markup Italic, Diff Changed
base0F = "#a3685a" # Deprecated, Opening/Closing Embedded Language Tags, e.g. <?php ?>
